"""empty message

Revision ID: 865cb431f6bf
Revises: a1c706d00f0e
Create Date: 2024-07-24 20:24:22.354651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865cb431f6bf'
down_revision = 'a1c706d00f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('gender', sa.String(length=25), nullable=False),
    sa.Column('eye_color', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav_chars',
    sa.Column('characters_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('characters_id', 'user_id')
    )
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_characters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_characters_pkey')
    )
    op.drop_table('fav_chars')
    op.drop_table('characters')
    # ### end Alembic commands ###
