"""empty message

Revision ID: d5ed5b7fef0f
Revises: 8616c14e4695
Create Date: 2024-07-25 20:47:33.688916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ed5b7fef0f'
down_revision = '8616c14e4695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_chars', schema=None) as batch_op:
        batch_op.drop_constraint('fav_chars_characters_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('fav_chars_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('fav_planets', schema=None) as batch_op:
        batch_op.drop_constraint('fav_planets_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('fav_planets_planets_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])

    with op.batch_alter_table('fav_ships', schema=None) as batch_op:
        batch_op.drop_constraint('fav_ships_ships_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('fav_ships_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'ships', ['ships_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_ships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fav_ships_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fav_ships_ships_id_fkey', 'ships', ['ships_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fav_planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fav_planets_planets_id_fkey', 'planets', ['planets_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fav_planets_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fav_chars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fav_chars_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fav_chars_characters_id_fkey', 'characters', ['characters_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
